const cfg=window.NBYN_CONFIG||{};const sb=window.supabase&&cfg.SUPABASE_URL.startsWith("http")?supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_KEY):null;
const $=s=>document.querySelector(s),money=n=>Number(n||0).toLocaleString("fr-FR")+" DA";let products=[];
$("#loginBtn").onclick=login;$("#logout").onclick=async()=>{if(sb)await sb.auth.signOut();location.reload()};
async function login(){if(!sb)return $("#loginMsg").textContent="ضع بيانات Supabase في assets/config.js";let r=await sb.auth.signInWithPassword({email:$("#email").value,password:$("#password").value});if(r.error){$("#loginMsg").textContent=r.error.message;return}await boot()}
async function boot(){let {data:{user}}=await sb.auth.getUser();if(!user){$("#login").classList.remove("hidden");$("#app").classList.add("hidden");return}
let p=await sb.from("profiles").select("role").eq("id",user.id).single();if(p.error||p.data?.role!=="admin"){await sb.auth.signOut();$("#loginMsg").textContent="هذا الحساب ليس مديراً.";return}
$("#login").classList.add("hidden");$("#app").classList.remove("hidden");show("dashboard")}
if(sb)sb.auth.getSession().then(({data:{session}})=>{if(session)boot()});
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");show(b.dataset.page)});
async function show(page){let t={dashboard:"لوحة التحكم",products:"المنتجات",orders:"الطلبات",customers:"العملاء",messages:"الرسائل",inventory:"المخزون",coupons:"الكوبونات",settings:"الإعدادات"};$("#title").textContent=t[page];if(page==="dashboard")dashboard();if(page==="products")productsPage();if(page==="orders")ordersPage();if(page==="customers")customersPage();if(page==="messages")messagesPage();if(page==="inventory")inventoryPage();if(page==="coupons")couponsPage();if(page==="settings")settingsPage()}
async function getProducts(){let r=await sb.from("products").select("*").order("created_at",{ascending:false});products=r.data||[];return products}
async function dashboard(){let [p,o]=await Promise.all([sb.from("products").select("id,stock"),sb.from("orders").select("id,total,status")]);let sales=(o.data||[]).reduce((a,x)=>a+Number(x.total||0),0);$("#page").innerHTML=`<div class="stats"><div class="stat"><small>المنتجات</small><strong>${(p.data||[]).length}</strong></div><div class="stat"><small>الطلبات</small><strong>${(o.data||[]).length}</strong></div><div class="stat"><small>المبيعات</small><strong>${money(sales)}</strong></div><div class="stat"><small>المخزون</small><strong>${(p.data||[]).reduce((a,x)=>a+Number(x.stock||0),0)}</strong></div></div><div class="panel"><h3>حالة النظام</h3><p>قاعدة البيانات متصلة. إدارة المنتجات والطلبات والمخزون والرسائل تعمل من Supabase مع صلاحية admin.</p></div>`}
async function productsPage(){let p=await getProducts();$("#page").innerHTML=`<div class="panel"><div class="panelHead"><h3>إدارة المنتجات</h3><button class="primary" onclick="productModal()">+ منتج</button></div><table><tr><th>الاسم</th><th>الفئة</th><th>السعر</th><th>المخزون</th><th></th></tr>${p.map(x=>`<tr><td>${x.name}</td><td>${x.category}</td><td>${money(x.price)}</td><td>${x.stock}</td><td><button class="danger" onclick="del('${x.id}')">حذف</button></td></tr>`).join("")}</table></div>`}
function productModal(){openModal("إضافة منتج",`<div class="form"><input id="pn" placeholder="اسم المنتج"><select id="pc"><option value="men">رجال</option><option value="women">نساء</option></select><input id="pp" type="number" placeholder="السعر"><input id="ps" type="number" placeholder="المخزون"><input id="pi" placeholder="رابط الصورة"><textarea id="pd" placeholder="الوصف"></textarea><button class="primary" onclick="add()">حفظ</button></div>`)}
async function add(){let r=await sb.from("products").insert({name:$("#pn").value,category:$("#pc").value,price:+$("#pp").value,stock:+$("#ps").value,image_url:$("#pi").value,description:$("#pd").value});if(r.error)return alert(r.error.message);closeModal();productsPage()}
async function del(id){if(!confirm("حذف المنتج؟"))return;let r=await sb.from("products").delete().eq("id",id);if(r.error)alert(r.error.message);else productsPage()}
async function ordersPage(){let r=await sb.from("orders").select("*").order("created_at",{ascending:false});$("#page").innerHTML=`<div class="panel"><h3>الطلبات</h3><table><tr><th>العميل</th><th>المجموع</th><th>الحالة</th><th>التاريخ</th></tr>${(r.data||[]).map(o=>`<tr><td>${o.customer_name}</td><td>${money(o.total)}</td><td><select onchange="status('${o.id}',this.value)"><option ${o.status==="new"?"selected":""}>new</option><option ${o.status==="confirmed"?"selected":""}>confirmed</option><option ${o.status==="preparing"?"selected":""}>preparing</option><option ${o.status==="shipped"?"selected":""}>shipped</option><option ${o.status==="delivered"?"selected":""}>delivered</option><option ${o.status==="cancelled"?"selected":""}>cancelled</option></select></td><td>${new Date(o.created_at).toLocaleString()}</td></tr>`).join("")}</table></div>`}
async function status(id,status){await sb.from("orders").update({status}).eq("id",id)}
async function customersPage(){let r=await sb.from("profiles").select("*").order("created_at",{ascending:false});$("#page").innerHTML=`<div class="panel"><h3>العملاء</h3><table><tr><th>الاسم</th><th>الهاتف</th><th>الصلاحية</th></tr>${(r.data||[]).map(x=>`<tr><td>${x.full_name||"—"}</td><td>${x.phone||"—"}</td><td>${x.role}</td></tr>`).join("")}</table></div>`}
async function messagesPage(){let r=await sb.from("messages").select("*").order("created_at",{ascending:false});$("#page").innerHTML=`<div class="panel"><h3>رسائل خدمة العملاء</h3><table><tr><th>الاسم</th><th>البريد</th><th>الرسالة</th><th>الحالة</th></tr>${(r.data||[]).map(x=>`<tr><td>${x.name}</td><td>${x.email}</td><td>${x.message}</td><td>${x.status}</td></tr>`).join("")}</table></div>`}
async function inventoryPage(){let p=await getProducts();$("#page").innerHTML=`<div class="panel"><h3>المخزون</h3><table><tr><th>المنتج</th><th>المخزون</th><th>الحالة</th></tr>${p.map(x=>`<tr><td>${x.name}</td><td>${x.stock}</td><td>${x.stock<10?"منخفض":"متوفر"}</td></tr>`).join("")}</table></div>`}
async function couponsPage(){let r=await sb.from("coupons").select("*").order("created_at",{ascending:false});$("#page").innerHTML=`<div class="panel"><div class="panelHead"><h3>الكوبونات</h3><button class="primary" onclick="couponModal()">+ كوبون</button></div><table><tr><th>الكود</th><th>الخصم</th><th>فعال</th><th>انتهاء</th></tr>${(r.data||[]).map(x=>`<tr><td>${x.code}</td><td>${x.discount_percent}%</td><td>${x.active?"نعم":"لا"}</td><td>${x.expires_at||"—"}</td></tr>`).join("")}</table></div>`}
function couponModal(){openModal("كوبون جديد",`<div class="form"><input id="cc" placeholder="CODE"><input id="cd" type="number" placeholder="نسبة الخصم"><input id="ce" type="datetime-local"><button class="primary" onclick="addCoupon()">حفظ</button></div>`)}
async function addCoupon(){let r=await sb.from("coupons").insert({code:$("#cc").value.toUpperCase(),discount_percent:+$("#cd").value,expires_at:$("#ce").value||null});if(r.error)alert(r.error.message);else{closeModal();couponsPage()}}
function settingsPage(){$("#page").innerHTML=`<div class="panel"><h3>إعدادات</h3><div class="notice">إعدادات Supabase موجودة في assets/config.js. استخدم Publishable/Anon key فقط في الواجهة، ولا تستخدم Service Role Key.</div></div>`}
function openModal(t,b){$("#modalTitle").textContent=t;$("#modalBody").innerHTML=b;$("#modal").classList.remove("hidden")}function closeModal(){$("#modal").classList.add("hidden")}$("#modalClose").onclick=closeModal;